# NUMPY

Numerical Python (NumPy)

Docs : https://numpy.org/

NumPy is the fundamental package for scientific computing with Python. The main benefit of Numpy is its powerful N-dimensional array object that it provides.

An array is collection of items stored at contiguous memory locations. The idea is to store multiple items of same type together.

NumPy offers comprehensive mathematical functions, random number generators, linear algebra routines, Fourier transforms, and more.

In [1]:
#for installing numpy 
!pip install numpy

In [1]:
#For importing numpy 
import numpy as np

In [4]:
#Basis
#To convert numpy array
my_list = [1,2,3]
n = np.array(my_list)
n     #We get a Positive Tuple, which is the main diff between normal list and numpy array/list 

array([1, 2, 3])

In [5]:
type(my_list)

list

In [6]:
type(n)  #In output, ndarray stands for N-dimensional array

numpy.ndarray

In [7]:
list_of_lists = np.array([[1,2,3],[4,5,6],[7,8,9]])
list_of_lists

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
#.shape is used to find the dimensions
list_of_lists.shape   

(3, 3)

In [11]:
#.arange gives us the same funcionality like range in python
#np.arange(n,m) gives us numbers from n to m but not including the number m
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
#if n in not given in np.arange(n,m) then python will assume it is from o to m
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
#if you want to skip some intervals in the arange then use np.arange(n,m,p) 
#where p is the interval between n and m
np.arange(2,15,2)

array([ 2,  4,  6,  8, 10, 12, 14])

In [18]:
#To generate an arrays of zeros use np.zeros(n)
zero = np.zeros(10)
zero

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [21]:
#For Multi-dimensional arange use np.zeros(n) or np.ones(n)
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [22]:
#To generate n*n matrix where diagonal elements are 1 and no diagonal elements are 0 then use np.eye(n)
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [23]:
#To count the number of elements in np array use len(np_array_name)
mn = np.arange(0,12)
print(mn)
print(len(mn))

[ 0  1  2  3  4  5  6  7  8  9 10 11]
12


In [24]:
#To replace the np array according to your shape use array_name.array(n,m)
mn.reshape(3,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [26]:
#To generate p evenely spaced values between n,m , use np.linspace(n,m,p)
o = np.linspace(0,7,10)
o

array([0.        , 0.77777778, 1.55555556, 2.33333333, 3.11111111,
       3.88888889, 4.66666667, 5.44444444, 6.22222222, 7.        ])

In [27]:
len(o)

10

In [30]:
o.reshape(5,2)

array([[0.        , 0.77777778],
       [1.55555556, 2.33333333],
       [3.11111111, 3.88888889],
       [4.66666667, 5.44444444],
       [6.22222222, 7.        ]])

In [31]:
o

array([0.        , 0.77777778, 1.55555556, 2.33333333, 3.11111111,
       3.88888889, 4.66666667, 5.44444444, 6.22222222, 7.        ])

In [33]:
#From the above two commands we can see that reshape will change the original array's shape
#To reshape and save it, we have to use array_name.resize(n,m)
o.resize(5,2)
print(o)

[[0.         0.77777778]
 [1.55555556 2.33333333]
 [3.11111111 3.88888889]
 [4.66666667 5.44444444]
 [6.22222222 7.        ]]


In [35]:
o  #Now its saved and reshaped/sized 

array([[0.        , 0.77777778],
       [1.55555556, 2.33333333],
       [3.11111111, 3.88888889],
       [4.66666667, 5.44444444],
       [6.22222222, 7.        ]])

In [39]:
#To generate random numbers in a shape of(n,m) use np.random.rand(3,2)
np.random.rand(3,2)
#Generated random numbers will be between 0 and 1
#It is in uniform distribution

array([[0.23245103, 0.68662084],
       [0.97093262, 0.89098877],
       [0.77295576, 0.78349492]])

In [41]:
np.random.randn(5,2)
#It is in 'Standard Uniform' distribution
#It can go beyond +/- 1

array([[ 0.93915854, -0.78834071],
       [-0.30508539, -1.52470203],
       [ 0.15011911,  0.43036727],
       [ 1.09622328,  1.21952259],
       [ 0.9683836 ,  1.59207137]])

In [43]:
#To generate n random numbers between a(inclusive),b(exclusive) use,
xy = np.random.randint(2,14,5)
xy

array([ 3,  2, 13,  6,  6])

In [46]:
#To generate random numbers and reshape them in in one command use np.random.randint(a,b,(n,m))
# where numbers between a(inclusive),b(exclusive) will be printed in the shape of (n,m)
tt =   np.random.randint(2,15,(4,3))
tt
#Number of elements printed will be n*m , in this above example it is 4*3 = 12 elements

array([[11,  7,  2],
       [ 3, 11,  9],
       [13,  4,  8],
       [12,  3, 11]])

In [47]:
#INDEXING AND SLICING

In [49]:
#LIKE IN PYTHON ARRAYS , INDEXING AND SLICING IS SAME IN NUMPY ARRAYS ALSO

In [51]:
xy = np.random.randint(2,14,5)
xy

array([11,  2, 10,  3,  2])

In [52]:
xy[1]

2

In [54]:
xy[2:5]

array([10,  3,  2])

In [55]:
xy[1:]

array([ 2, 10,  3,  2])

In [56]:
xy[::-1]

array([ 2,  3, 10,  2, 11])

In [58]:
ab = np.random.randint(2,20,(5,5))
ab

array([[10,  8,  2, 10,  2],
       [ 6,  3,  7,  5,  6],
       [ 9, 14, 12,  8, 19],
       [ 8, 17,  3, 17,  9],
       [17, 13,  5, 18, 13]])

In [64]:
#To select a range of rows or column use,
ab[2,1:4]

array([14, 12,  8])

In [66]:
ab>5 #Conditional indexing

array([[ True,  True, False,  True, False],
       [ True, False,  True, False,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True, False,  True,  True],
       [ True,  True, False,  True,  True]])

In [67]:
ab[ab>5]

array([10,  8, 10,  6,  7,  6,  9, 14, 12,  8, 19,  8, 17, 17,  9, 17, 13,
       18, 13])

In [70]:
#TO replace all numbers/Braodcast these numbers according to a condtion ,then do,
ab[ab>5] = 5
ab
#All the numbers greater than 5 are replaced by 5

array([[5, 5, 2, 5, 2],
       [5, 3, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 3, 5, 5],
       [5, 5, 5, 5, 5]])

In [80]:
#Copying a array
print("xy =",xy)
xy1 = xy
print("xy1 =",xy1)

#OR
#xy  will not be destroyed 
xy2 = xy.copy()
print("xy2 =",xy2)

xy = [11  2 10  3  2]
xy1 = [11  2 10  3  2]
xy2 = [11  2 10  3  2]


In [22]:
#Some basic math operation by numpy
minimum = np.min(std)
maximum = np.max(std)
standard_deviation = np.std(std)
variance = np.var(std)
mean = np.mean(std)